modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Creatures-5/VehicleCore/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "vehiclecore"
version = "${version}"
displayName = "VehicleCore"
displayURL = "https://github.com/Creatures-5/VehicleCore"
authors = "Creatures-5"
description = "A fork of vehiclecore"
logoFile = "icon.png"
itemIcon = "vehiclecore:biplane"

[[dependencies.vehiclecore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vehiclecore]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vehiclecore]]
modId = "ad_astra"
mandatory = false
versionRange = "[1.15.6,)"
ordering = "NONE"
side = "BOTH"
